services:
  - type: web
    name: orbit-proxy-static
    runtime: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist-render
    headers:
      - path: /*
        name: Cross-Origin-Opener-Policy
        value: same-origin
      - path: /*
        name: Cross-Origin-Embedder-Policy
        value: require-corp
      - path: /*
        name: Cache-Control
        value: no-cache
